name: CI Pipeline Demonstration

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test Orchestration Step
        run: echo "CI/CD Pipeline triggered successfully!"
        # ------------------ CD STAGE ------------------
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4jobs:
  # ------------------ CI STAGE ------------------
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node_version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Automated Tests
        run: npm test

      - name: Build Game Production Package
        run: npm run build

      - name: Setup GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

  # ------------------ CD STAGE ------------------
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4